CREATE TABLE IF NOT EXISTS PRODUTO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(30) UNIQUE NOT NULL,
	DESCRICAO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
	ID_PRODUTO INT PRIMARY KEY,
	QUANTIDADE INT NOT NULL,
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);

CREATE TABLE IF NOT EXISTS RESERVA (
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ID_PEDIDO, ID_PRODUTO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);
